spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/homework_5?characterEncoding=UTF8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    cache: false
server:
  port: 8081
